version: "3.8"

services:
  php:
    build: .
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:80"
# docker-compose down
# docker-compose build --no-cache
# docker-compose up -d
